name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

permissions:
  id-token: write
  contents: read

env:
    MONGO_URI: ${{ secrets.MONGO_URI }}
    MONGO_USERNAME:  ${{ secrets.MONGO_USERNAME }}
    MONGO_PASSWORD:  ${{ secrets.MONGO_PASSWORD }}


jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            nodejs_version: [18, 20]
            operating_system: [ubuntu-latest]
        runs-on: ${{ matrix.operating_system }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7

            - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
              uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.nodejs_version }}

            - name: Cache NPM dependencies
              uses: actions/cache@v6
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
            
            - name: Install Dependencies
              run: npm install

            - name: Unit Testing
              id: nodejs-unit-test-step
              run: npm test

            - name: Archive Test result
              if: always ()
              uses: actions/upload-artifact@v7
              with:
                name: Mocha-Test-Result
                path: test-results.xml

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7

            - name: Setup NodeJS Version - 18
              uses: actions/setup-node@v6
              with:
                node-version: 18
                
            - name: Cache NPM dependencies
              uses: actions/cache@v6
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
                
            - name: Install Dependencies
              run: npm install

            - name: Check Code Coverage
              continue-on-error: true
              run: npm run coverage

            - name: Archive Test Result
              uses: actions/upload-artifact@v7
              with:
                name: Code-Coverage-Result
                path: coverage
                retention-days: 5

    docker:
        name: Containerization
        needs: [unit-testing, code-coverage]
        permissions:
          packages: write
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v7

          - name: Log in to Docker Hub
            uses: docker/login-action@v4
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Log in to GitHub Conatiner Registry
            uses: docker/login-action@v4
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
              
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v4
            
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v4

          - name: Docker Build For Testing
            uses: docker/build-push-action@v7
            with:
              context: .
              load: true
              push: false
              tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          - name: Run Container and Test `/live` Endpoint
            run: |
              docker images
              docker run --name solay-system-app -d \
                   -p 3000:3000 \
                   -e MONGO_URI=$MONGO_URI \
                   -e MONGO_USERNAME=$MONGO_USERNAME \
                   -e MONGO_PASSWORD=$MONGO_PASSWORD \
                   ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

              echo "Verifying /live endpoint"
              wget -q -O - http://127.0.0.1:3000/live | grep live

          - name:  Docker Build and Push to Docker Hub & GHCR
            uses: docker/build-push-action@v7
            with:
              context: .
              push: true
              tags: |
                ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
                ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}

    dev-deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v7

        - name: Configure AWS (OIDC)
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: ${{ vars.AWS_REGION }}

        - name: Install Kubectl CLI
          uses: azure/setup-kubectl@v4
          with:
            version: v1.36.0

        - name: Configure kubeconfig
          run: | 
            aws eks update-kubeconfig --region ap-south-1 --name solar-system

        - name: Verify Cluster Connection
          run: | 
            kubectl version 
            echo "------------------------------------------" 
            kubectl get nodes 
            echo "------------------------------------------"
            kubectl get namespaces